omegaup/quark

- .travis.yml
This change makes Travis use git2go v29 instead of... whatever it was
using before.
> Use the correct version of git2go

- runner/ci/ci.go
This change makes it so that if a validator language is not explicitly
provided to settings.json, it tries to guess the language of the
validator based on the filename.
> Try a bit harder to find the validator language

- cmd/omegaup-grader/ci.go
- cmd/omegaup-runner/main.go
- runner/ci/ci.go
- runner/ci/ci_test.go
It doesn't make too much sense to have duplication of solutions and .out
generation.
> Use solutions/solution.* for the .out generation

- cmd/omegaup-runner/main.go
- runner/ci/ci.go
- runner/ci/ci_test.go
- runner/sandbox.go
This allows for .out files to be generated in directories other than
`cases/`. This is useful in CI contexts.
> Allow .out files to be generated in other directories 

- cmd/validator/main.go
- common/literalinput.go
- common/literalinput_test.go
- common/problemsettings.go
- grader/input_test.go
- grader/queue_test.go
- runner/ci/ci.go
- runner/ci/ci_test.go
- runner/input_test.go
- runner/runner.go
- runner/runner_test.go
- runner/validator.go
- runner/validator_test.go
This change adds the `GroupScorePolicy` field for the validator
settings. This assigns the minimum of all the individual cases' scores
multiplied by the weight of the group.
> Add a way to choose the minimum score for a group 

- common/literalinput.go
This change fixes a typo in the `group_score_policy` entry in the
literal validator settings.
> Fix typo in `group_score_policy`

- runner/runner.go
- runner/runner_test.go
This change fixes the `sum-if-not-zero` group score policy, since it was
broken since yesterday. Also adds a test for it to avoid regressions.
Fixes: https://github.com/omegaup/omegaup/issues/5658
> Fix the `sum-if-not-zero` group score policy

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Dockerfile.prebuild
- cmd/omegaup-grader/ci.go
- cmd/omegaup-grader/main.go
- common/problemfiles.go
- go.mod
- go.sum
- grader/grader_test.go
- grader/input.go
Now that libgit2 v1.2.0 has been released, we no longer need to have a
fork (for now). #minor
> Update git2go to the latest version

- go.mod
- go.sum
This should make it possible for downstream modules to import the
newrelic tracing module. #minor
> Update go-base to the lastest and greatest

- cmd/omegaup-grader/frontend_handler.go
- cmd/omegaup-grader/frontend_handler_test.go
- grader/queue.go
This change does a little refactor so that both the Runs and Submissions
tables are updated inside a transaction.
> Updating the denormalized Submissions fields too

- .vscode/settings.json
- runner/ci/ci.go
- runner/ci/ci_test.go
Feature parity with polygon: https://ali-ibrahim137.github.io/competitive/programming/2020/09/27/polygon-codeforces.html (ctrl+f: invalid)
The idea is that we should also be able to test _input validators_ themselves, by optionally having a set of _known_ invalid cases that the validator should reject.
(Also adds a .vscode file to the project so building/testing works with the official golang extension)
> CI: Allow checking input validators against known invalid cases

- cmd/omegaup-grader/runner_handler.go
- cmd/omegaup-runner/service.go
This change makes it such that the runners will always be sending stuff
over the network every 15s to minimize the chance of timing out and
being forcefully disconnected.
Fixes: https://github.com/omegaup/omegaup/issues/6274
> Try harder to keep the connection alive

- common/problemsettings.go
- runner/ci/ci.go
- runner/ci/ci_test.go
Faltaba pasar el GroupScorePolicy a los CI runs.
También por consistencia cambia `maxScore` por `max_score`; el resto de las llaves de ese json son con `snake_case` (somos los únicos usuarios: prometo no hacer breaking changes tan horribles si hay otra gente usando las cosas 😬😇)
> Add support for group-score-policy; rekey maxScore

- runner/runner.go
- runner/runner_test.go
En particular, los newlines al final de los archivos estaban haciendo tronar algunos tests porque el string que tenía esperado era en medio de una línea y pues fallaba porque no encontraba el newline .-.
https://github.com/omegaup/ofmi-2022/runs/4884915041?check_suite_focus=true#step:10:137
El string en cuestión era el que estaba en medio de las comillas: `"aa" [REDACTED] "aa"`.
> Trim whitespace on stderr validation

- runner/runner.go
Previously, when a compiler error happened, the generated .zip file had
nothing in it (in fact, it was an empty file).
> Always updating the zip with files

- go.mod
- go.sum
- runner/runner.go
- runner/sandbox.go
This change makes the omegajail invocation log display the correctly
escaped string.
> Make the sandbox invocation log actually work

- docker/Dockerfile
This change bumps omegajail (the binary, not the rootfs) to v3.9.1 so
that it can have the `--allow-sigsys-fallback` flag.
> Bump omegajail to v3.9.1

- cmd/omegaup-runner/main.go
- runner/sandbox.go
This is needed for the CI mode to work well locally in older (pre-5.13)
Linux kernels, like the ones in WSL or some versions of Docker-in-Mac.
> Allow omegajail to use the `SIGSYS` fallback when in CI mode

- common/context.go
- common/literalinput.go
- common/problemsettings.go
- runner/runner.go
- runner/runner_test.go
- runner/sandbox.go
- runner/sandbox_test.go
Intento de resolver #32. La idea es que se valga tener archivos grandes, nomás no muchos.
(De hecho esto es mejoría: creo que no había impedimento de, digamos, hacer un problema con 100 casos que corran súper rápido con output de 2MiB cada uno)
> Overall Output Limit

- .github/workflows/release.yml
Not doing this will cause failures to compile things.
> Make the release steps also run Go 1.19

- go.mod
- go.sum
- grader/input_test.go
githttp now gained the ability to cache lockfiles and repositories.
> Upgrade githttp

- cmd/omegaup-grader/metrics.go
- cmd/omegaup-grader/runner_handler.go
This change allows prometheus to do discovery of runners without needing to do Azure service discovery.
> Add a way to export runners

- cmd/omegaup-runner/main.go
- cmd/omegaup-runner/service.go
- common/context.go
This allows the grader to correctly represent the runner's public server.
> Make the runner publish its own public IP when requesting

- cmd/omegaup-grader/runner_handler.go
The remote address as reported by `r.RemoteAddr` is not useful because it's the ingress internal address. This change now uses the self-reported public IP address from the runner.
> Publish the self-reported runner public IP

- grader/artifacts.go
Now that we save all the submissions in this bucket, we don't need to keep the old one around for anything.
> Finish the `omegaup-submissions` migration

- .github/workflows/ci.yml
- .github/workflows/release.yml
pin the version being used explicitly (i.e. the old one that got bumped when github changed the meaning of `ubuntu-latest`)
> pin github action container version

- runner/sandbox.go
Previously we were using `omegajailParams`, which don't have the extra flags, but were logging `omegajailFullParams`!
Now we use and log the same one.
> Using the correct variable to invoke omegajail

- runner/sandbox.go
Turns out that `exec.Command` doesn't like having the first arg there.
> Fix the omegajail invocation

- docker/Dockerfile.backend
This change now allows compilation and testing in M1 macOS.
> libinteractive bump

- cmd/omegaup-runner/main.go
- runner/sandbox.go
This makes compilation errors appear front and center when they occur.
> Make compilation errors more visible

- runner/ci/ci.go
This section did not include the interactive options, so we were failing to compile when generating `.out`s.
> Have the `OutGeneratorConfig.Input` also include `Interactive`

- docker/Dockerfile
This change bumps omegajail so that we can finally run interactive problems again, since they require compiling C++ and assembly files in the same commandline invocation.
> Bump omegajail to v3.10.2

- docker/Dockerfile
This is needed to run libinteractive problems.
> Create `/dev/null` in the container

- docker/Dockerfile
- runner/sandbox.go
Libinteractive problems required bind-mounting, but that's not enabled without a sandbox.
This change falls back to symlinking when the sandboxing is disabled.
> Allow running libinteractive problems without sandboxing

- docker/Dockerfile
This change bumps the omegajail version so that it can skip setting up the seccomp sandbox when needed.
> Bump omegajail version

- cmd/omegaup-grader/frontend_handler.go
- cmd/omegaup-grader/frontend_handler_test.go
Added the verdict "WA" when score is 0 in contest mode "All or nothing"
Fixes: https://github.com/omegaup/omegaup/issues/7000
> Fixed the verdict in contest mode all or nothing when score is 0

- cmd/omegaup-runner/main.go
ifconfig.me changed their API. Now they need `/ip` to get the IP from Golang.
> [runner] Fix IP getting
