omegaup/quark

cmd/omegaup-grader/frontend_handler.go, grader/queue.go
These changes are no longer needed. Instead, it will be necesary make
some changes in the frontend
=> Revert changes related with partial score

cmd/omegaup-grader/ephemeral_test.go, cmd/omegaup-grader/frontend_handler.go, cmd/omegaup-grader/frontend_handler_test.go, cmd/omegaup-grader/main.go
This adds some much-needed tests for the frontend_handler.go file.
=> Adding tests for frontend_handler.go

cmd/omegaup-grader/frontend_handler_test.go
Intenté replicar el test de broadcastRun con un par de escenarios en donde se 
vea la diferencia en el campo de score y contest_score, pero obtengo el mismo
resultado en las dos pruebas. 
¿Hay algo que no estoy considerando?
=> Adding table-driven test to bradcastRun function

cmd/omegaup-grader/frontend_handler.go
This change uses submission_id instead of run_id to implement the run
queue. This is because when a problem is rejudged due to a new version
being added, it adds rows to the Runs table with higher run_id values,
making new non-rejudged runs wait unnecessarily.
=> Use submission_id instead of run_id for the queue

.github/workflows/ci.yml, .github/workflows/release.yml, cmd/omegaup-grader/frontend_handler.go, cmd/omegaup-grader/frontend_handler_test.go, cmd/omegaup-grader/runner_handler.go
This should take care of transactions that fail due to lock timeouts.
=> Attempt to retry retriable database errors

.github/workflows/ci.yml, .github/workflows/release.yml, cmd/omegaup-broadcaster/main.go, cmd/omegaup-grader/main.go, cmd/omegaup-runner/main.go, docker/Dockerfile.backend, go.mod, go.sum
This change upgrades go to the lastest and greatest: 1.17 #minor
=> Upgrade to Go 1.17

.github/workflows/ci.yml, .github/workflows/release.yml, Dockerfile.prebuild, cmd/omegaup-grader/ci.go, cmd/omegaup-grader/main.go, common/problemfiles.go, go.mod, go.sum, grader/grader_test.go, grader/input.go
This change upgrades both libraries to their latest and greatest.
=> Upgrade git2go and go-base

.github/workflows/release.yml
This will allow us to not do this by hand.
=> Automatically uprev the sandbox image versions

.github/workflows/release.yml
=> Fix the release script

go.mod, go.sum, grader/input_test.go
This change makes the grader wrap more handlers with the tracing wrapper
as well as adding better context wrapping so that logs can be correlated
correctly.
=> Improve grader tracing

common/context.go
=> Remove WriteGradeFiles

broadcaster/subscriber.go, cmd/omegaup-broadcaster/main.go
This change allows SSE callers to add the `Authorization: token ${apiToken}` header that they can send today to the frontend. WebSocket callers can't send headers, so they can use the `api_token` cookie to send it.
Fixes: #59
=> Allow broadcaster authorization through API tokens

common/problemsettings.go, go.mod, go.sum, runner/ci/ci.go, runner/ci/ci_test.go
Adds a new parameter to `tests.json` to check if the max score adds up to the expected value.
=> CI: Support for validating total case sum

common/literalinput.go, common/literalinput_test.go, runner/ci/ci.go, runner/ci/ci_test.go, runner/runner.go, runner/runner_test.go, runner/sandbox_test.go
=> Support for .expected-failure files

common/literalinput.go, runner/runner_test.go
This change prevents compilation errors for C++20.
=> Use the `.cpp` extension for C++20 languages

cmd/omegaup-grader/frontend_handler.go, cmd/omegaup-grader/frontend_handler_test.go, runner/runner.go
This change now makes grader populate the Runs_Groups table every time a run is graded.
=> Populate Runs_Groups

cmd/omegaup-grader/frontend_handler.go, cmd/omegaup-grader/frontend_handler_test.go, grader/queue.go
Part of https://github.com/omegaup/omegaup/issues/6449
=> Renamed partialScore field with scoreMode

cmd/omegaup-grader/metrics.go, cmd/omegaup-grader/runner_handler.go
=> Export runner metrics with the hostname

grader/artifacts.go
This is a migration commit that helps publish objects to both the `omegaup-backup` and the `omegaup-submissions` buckets.
=> Publish the s3 objects to `omegaup-submissions` too

docker/Dockerfile
This should display the errnos a bit nicer.
=> Bump omegajail

docker/Dockerfile
This change also updates libinteractive in the runner-ci image.
=> libinteractive bump

docker/Dockerfile
=> Fix a syntax error in the Dockerfile

cmd/omegaup-grader/frontend_handler.go, cmd/omegaup-grader/frontend_handler_test.go
Fixing a key in order to match the name with the frontend key
=> Renamed the key score_per_group with score_by_group

cmd/omegaup-runner/main.go
ipconfig.me is returning invalid IPs for some reason.
=> Fix invalid IP
